config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  root "home#index"

  resources :users

  resources :playlists

  resources :songs do
    get :playlistadd, on: :member
    get :setplaylist, on: :member
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  created_at :datetime         not null
#  id         :bigint(8)        not null, primary key
#  song_id    :bigint(8)
#  title      :string
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#
# Indexes
#
#  index_playlists_on_song_id  (song_id)
#  index_playlists_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (song_id => songs.id)
#  fk_rails_...  (user_id => users.id)
#


class Playlist < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :songs
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  created_at :datetime         not null
#  id         :bigint(8)        not null, primary key
#  title      :string
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#
# Indexes
#
#  index_songs_on_user_id  (user_id)
#


class Song < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :playlists

  has_one_attached :song_file
  has_one_attached :thumbnail

  validates_presence_of :user, :title


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  created_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  id                     :bigint(8)        not null, primary key
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  song_id                :bigint(8)
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_song_id               (song_id)
#
# Foreign Keys
#
#  fk_rails_...  (song_id => songs.id)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :songs
  has_many :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# Renders the home page.
class HomeController < ApplicationController
  def index
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :find_playlist
  def show
  end


  private

  def find_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  respond_to :html, :js

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  respond_to :html, :js

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :create, :new, :destroy]

  # GET /songs
  def index
    @songs = Song.all

  @user_playlists = current_user.playlists
  end

  # GET /songs/1
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  def create
    @song = current_user.songs.build(song_params)
    if @song.save
      redirect_to @song, notice: 'Song was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /songs/1
  def update
    if @song.update(song_params)
      redirect_to @song, notice: 'Song was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /songs/1
  def destroy
    @song.destroy
    redirect_to songs_url, notice: 'Song was successfully destroyed.'
  end

  def playlistadd
    @playlist = Playlist.find(params[:playlist_id])
    @song = Song.find(params[:id])

    @playlist.songs << @song


    respond_to do |format|
      format.js # actually means: if the client ask for js -> return file.js
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_song
    @song = Song.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def song_params
    params.require(:song).permit(:title, :song_file, :thumbnail)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(name = nil, options = nil, html_options = nil, &block)
    active_class = html_options[:active] || "active"
    html_options.delete(:active)
    html_options[:class] = "#{html_options[:class]} #{active_class}" if current_page?(options)
    link_to(name, options, html_options, &block)
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/retina_image_helper.rb
module RetinaImageHelper
  # Like the Rails image_tag, but adds a srcset attribute with an @2x version
  # of the image, thereby ensuring the image looks great on retina devices.
  # Assumes that the retina version of the image is named the same with "@2x"
  # before the extension, like "image@2x.png". For example:
  #
  #   <%= retina_image_tag("logo.png") %>
  #
  # Produces:
  #
  #   <img src="/assets/logo.png"
  #        srcset="/assets/logo.png 1x,/assets/logo@2x.png 2x">
  #
  # The srcset attribute is supported by modern desktop browsers and iOS 8+.
  def retina_image_tag(src, options={})
    src_1x = image_path(src)
    src_2x = image_path(src.sub(/^(.*)(\.[^\.]+)$/, '\1@2x\2'))
    srcset = "#{src_1x} 1x,#{src_2x} 2x"

    image_tag(src, options.reverse_merge(srcset: srcset, alt: ""))
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
- provide(:title, "Home")

.ui.container.musi_rock_brand
  %h1.ui.header.aligned.centered
    MusiRock
    .sub.header
      Your Favorite Rock Music

.ui.container.index-header
  .ui.container
    %h5.ui.header.aligned.centered What would you like listen to today?
    .ui.search
      .ui.icon.input
        %input.prompt{:placeholder => "Search by titles, authors, collections..", :type => "text"}/
        %i.search.icon
      .results

app/views/layouts/_navbar.html.haml
.ui.segment.musirock_menu
  .ui.secondary.menu

    .left.menu
      .item
        %h1 MUSIROCK

      =active_link_to 'Home', root_path, class:'item'
      =active_link_to 'Featured', songs_path, class:'item'
      %a.item
        Collection

    .right.menu
      .item
        .ui
          =link_to 'Add song', new_song_path, class:'ui button'
      .item
        .ui.icon.input
          %input{type:"text", placeholder:"Search..."}
          %i.search.link.icon

      -if !user_signed_in?
        .item
          .ui.buttons
            =link_to "Log in", new_user_session_path, class:'ui button', id:'login_button', remote: true
            .or
            =link_to "Sign up", new_user_registration_path, class:'ui button', id:'register_button', remote: true
      -else
        .item
          .ui.menu
            .ui.dropdown.item
              =current_user.email
              %i.dropdown.icon
              .menu
                =link_to 'Profile', user_path(current_user), class:'item'
                %a.item Social
                =link_to 'Log out', destroy_user_session_path, class:'item', method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    / Musi Rock <haml_loud> Rails.application.config.version </haml_loud> (<haml_loud> l(Rails.application.config.version_time) </haml_loud>)
    = stylesheet_link_tag("application",media: "all", "data-turbolinks-track" => "reload")
    = javascript_include_tag("application", "data-turbolinks-track" => "reload")
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "MusiRock", :name => "apple-mobile-web-app-title"}
    = csrf_meta_tags
    = csp_meta_tag
    %title
      = strip_tags(yield(:title)) + " – " if content_for?(:title)
      MusiRock

  %body
    = render "layouts/navbar"
    = render "shared/modal"
    = render "shared/flash"
    = yield

app/views/playlists/show.html.haml
.ui.container.segment
  =@playlist.title

  -@playlist.songs.each do |s|
    %li=link_to s.title, s

app/views/shared/_flash.html.haml
= semantic_flash

app/views/shared/_modal.html.haml
.ui.basic.modal
  .content
    #modal_content

app/views/songs/_form.html.haml
.ui.container.segment.very.padded
  = form_for @song, html: {class:'ui form musi-form' } do |f|
    - if @song.errors.any?
      #error_explanation
        %h2= "#{pluralize(@song.errors.count, "error")} prohibited this song from being saved:"
        %ul
          - @song.errors.full_messages.each do |message|
            %li= message
    .field
      .ui.labeled.input
        .ui.label
          = f.label :title
        = f.text_field :title, placeholder: 'Title of the new song'

    .field
      .ui.labeled.input
        .ui.label
          = f.label :thumbnail
        = f.file_field :thumbnail

    .field
      .ui.labeled.input
        .ui.label
          = f.label :song_file
        = f.file_field :song_file

    .actions
      = f.submit 'Save', class: 'ui button musi-button'

app/views/songs/_link.html.haml
= link_to '+', playlistadd_song_path(@song), class:'button ui'

app/views/songs/_song.html.haml
.card
  .image
    %img{:src => "#{url_for(song.thumbnail.attachment)}"}/
  .content
    %h5.center.aligned= song.title
    .description
      -#song description
  .extra.content.center.aligned
    =audio_tag url_for(song.song_file.attachment), controls: true
  .extra.content
    .ui.buttons.mini.four
      = link_to 'Show', song , class:'button ui'
      = link_to 'Edit', edit_song_path(song), class:'button ui '
      = link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' }, class:'button ui'

  .extra.content
    .ui.buttons.two.small
      = select_tag "playlist_#{song.id}", options_from_collection_for_select(@user_playlists, 'id', 'title'), class:'button ui playlist_select', include_blank: '+', name: "#{song.id}"
    %div{id: "button_add#{song.id}"}


    %H2 Song is in these playlists
    -@user_playlists.includes(:songs).where.not(songs: { id: song.id }).each do |p|
      =p.title

app/views/songs/edit.html.haml
%h1 Editing song

= render 'form'

= link_to 'Show', @song
\|
= link_to 'Back', songs_path

app/views/songs/index.html.haml
.ui.aligned.centered.page-container
  -if @songs.any?
    %h1.ui.center.aligned.header.white-header Our songs list
    .ui.container.new-song-action
      .buttons
        = link_to 'Add new song', new_song_path, class:'button ui musi-button'

    .ui.horizontal.segment.very.padded
      .ui.link.cards.six
        =render @songs
  -else
    %h1.ui.center.aligned.header.white-header We dont have any songs yet! You can add one!

app/views/songs/new.html.haml
.ui.container.page-container
  .ui.huge.header.white-header.aligned.centered.very.padded
    %h1 New song

  .ui.horizontal.segment.container
    = render 'form'

  .ui.buttons
    = link_to 'Back', songs_path, class:'ui button musi-button'

app/views/songs/playlistadd.js.erb
$("#button_add<%= @song.id %>").html(" <%= 'Song added to ' + @playlist.title %>  ")

app/views/songs/show.html.haml
%p#notice= notice


=audio_tag url_for(@song.song_file), controls: true, autoplay: true

= link_to 'Edit', edit_song_path(@song)
\|
= link_to 'Back', songs_path

app/views/users/show.html.haml
.ui.container.segment
  =@user.email


.ui.container.segment
  .ui.header
    %h2 User playlists
    .ui.list
      -@user.playlists.each do |p|
        %li=link_to p.title, p